# Site settings
title: "nawalog"
description: "いろいろ書きます"
baseurl: ""
title_description: "Linuxとかリフレクビートとかがすきです"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
github_repository: https://github.com/3nawa-kun/3nawa-kun.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: dj_minawa
github_username:  3nawa-kun
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
