# Site settings
title: "nawalog"
description: "いろいろ書きます"
title_description: "Linuxとかリフレクビートとかがすきです"
title_image: "https://pbs.twimg.com/profile_images/683995605224427520/w0fqH2Z3_400x400.png"
github_repository: https://github.com/3nawa-kun/3nawa-kun.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: 370kun
github_username:  3nawa-kun

# Footer
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
